namespace decomplex.Finance
{
    /// <summary>
    /// Currency types.
    /// The enum was generated by CurrencyTypeCreator from data
    /// http://www.currency-iso.org/dam/downloads/lists/list_one.xml
    /// </summary>
    public enum CurrencyType
    {
        [CurrencyCountry("UNITED ARAB EMIRATES (THE)")]
        [CurrencyDefinition("AED", "UAE Dirham", "784", 2)]
        AED = 784,
        [CurrencyCountry("AFGHANISTAN")]
        [CurrencyDefinition("AFN", "Afghani", "971", 2)]
        AFN = 971,
        [CurrencyCountry("ALBANIA")]
        [CurrencyDefinition("ALL", "Lek", "008", 2)]
        ALL = 008,
        [CurrencyCountry("ARMENIA")]
        [CurrencyDefinition("AMD", "Armenian Dram", "051", 2)]
        AMD = 051,
        [CurrencyCountry("CURAÇAO")]
        [CurrencyCountry("SINT MAARTEN (DUTCH PART)")]
        [CurrencyDefinition("ANG", "Netherlands Antillean Guilder", "532", 2)]
        ANG = 532,
        [CurrencyCountry("ANGOLA")]
        [CurrencyDefinition("AOA", "Kwanza", "973", 2)]
        AOA = 973,
        [CurrencyCountry("ARGENTINA")]
        [CurrencyDefinition("ARS", "Argentine Peso", "032", 2)]
        ARS = 032,
        [CurrencyCountry("AUSTRALIA")]
        [CurrencyCountry("CHRISTMAS ISLAND")]
        [CurrencyCountry("COCOS (KEELING) ISLANDS (THE)")]
        [CurrencyCountry("HEARD ISLAND AND McDONALD ISLANDS")]
        [CurrencyCountry("KIRIBATI")]
        [CurrencyCountry("NAURU")]
        [CurrencyCountry("NORFOLK ISLAND")]
        [CurrencyCountry("TUVALU")]
        [CurrencyDefinition("AUD", "Australian Dollar", "036", 2)]
        AUD = 036,
        [CurrencyCountry("ARUBA")]
        [CurrencyDefinition("AWG", "Aruban Florin", "533", 2)]
        AWG = 533,
        [CurrencyCountry("AZERBAIJAN")]
        [CurrencyDefinition("AZN", "Azerbaijanian Manat", "944", 2)]
        AZN = 944,
        [CurrencyCountry("BOSNIA AND HERZEGOVINA")]
        [CurrencyDefinition("BAM", "Convertible Mark", "977", 2)]
        BAM = 977,
        [CurrencyCountry("BARBADOS")]
        [CurrencyDefinition("BBD", "Barbados Dollar", "052", 2)]
        BBD = 052,
        [CurrencyCountry("BANGLADESH")]
        [CurrencyDefinition("BDT", "Taka", "050", 2)]
        BDT = 050,
        [CurrencyCountry("BULGARIA")]
        [CurrencyDefinition("BGN", "Bulgarian Lev", "975", 2)]
        BGN = 975,
        [CurrencyCountry("BAHRAIN")]
        [CurrencyDefinition("BHD", "Bahraini Dinar", "048", 3)]
        BHD = 048,
        [CurrencyCountry("BURUNDI")]
        [CurrencyDefinition("BIF", "Burundi Franc", "108", 0)]
        BIF = 108,
        [CurrencyCountry("BERMUDA")]
        [CurrencyDefinition("BMD", "Bermudian Dollar", "060", 2)]
        BMD = 060,
        [CurrencyCountry("BRUNEI DARUSSALAM")]
        [CurrencyDefinition("BND", "Brunei Dollar", "096", 2)]
        BND = 096,
        [CurrencyCountry("BOLIVIA (PLURINATIONAL STATE OF)")]
        [CurrencyDefinition("BOB", "Boliviano", "068", 2)]
        BOB = 068,
        [CurrencyCountry("BOLIVIA (PLURINATIONAL STATE OF)")]
        [CurrencyDefinition("BOV", "Mvdol", "984", 2)]
        BOV = 984,
        [CurrencyCountry("BRAZIL")]
        [CurrencyDefinition("BRL", "Brazilian Real", "986", 2)]
        BRL = 986,
        [CurrencyCountry("BAHAMAS (THE)")]
        [CurrencyDefinition("BSD", "Bahamian Dollar", "044", 2)]
        BSD = 044,
        [CurrencyCountry("BHUTAN")]
        [CurrencyDefinition("BTN", "Ngultrum", "064", 2)]
        BTN = 064,
        [CurrencyCountry("BOTSWANA")]
        [CurrencyDefinition("BWP", "Pula", "072", 2)]
        BWP = 072,
        [CurrencyCountry("BELARUS")]
        [CurrencyDefinition("BYN", "Belarusian Ruble", "933", 2)]
        BYN = 933,
        [CurrencyCountry("BELARUS")]
        [CurrencyDefinition("BYR", "Belarusian Ruble", "974", 0)]
        BYR = 974,
        [CurrencyCountry("BELIZE")]
        [CurrencyDefinition("BZD", "Belize Dollar", "084", 2)]
        BZD = 084,
        [CurrencyCountry("CANADA")]
        [CurrencyDefinition("CAD", "Canadian Dollar", "124", 2)]
        CAD = 124,
        [CurrencyCountry("CONGO (THE DEMOCRATIC REPUBLIC OF THE)")]
        [CurrencyDefinition("CDF", "Congolese Franc", "976", 2)]
        CDF = 976,
        [CurrencyCountry("CHILE")]
        [CurrencyDefinition("CLF", "Unidad de Fomento", "990", 4)]
        CLF = 990,
        [CurrencyCountry("CHILE")]
        [CurrencyDefinition("CLP", "Chilean Peso", "152", 0)]
        CLP = 152,
        [CurrencyCountry("CHINA")]
        [CurrencyDefinition("CNY", "Yuan Renminbi", "156", 2)]
        CNY = 156,
        [CurrencyCountry("COLOMBIA")]
        [CurrencyDefinition("COP", "Colombian Peso", "170", 2)]
        COP = 170,
        [CurrencyCountry("COLOMBIA")]
        [CurrencyDefinition("COU", "Unidad de Valor Real", "970", 2)]
        COU = 970,
        [CurrencyCountry("COSTA RICA")]
        [CurrencyDefinition("CRC", "Costa Rican Colon", "188", 2)]
        CRC = 188,
        [CurrencyCountry("CUBA")]
        [CurrencyDefinition("CUC", "Peso Convertible", "931", 2)]
        CUC = 931,
        [CurrencyCountry("CUBA")]
        [CurrencyDefinition("CUP", "Cuban Peso", "192", 2)]
        CUP = 192,
        [CurrencyCountry("CABO VERDE")]
        [CurrencyDefinition("CVE", "Cabo Verde Escudo", "132", 2)]
        CVE = 132,
        [CurrencyCountry("CZECH REPUBLIC (THE)")]
        [CurrencyDefinition("CZK", "Czech Koruna", "203", 2)]
        CZK = 203,
        [CurrencyCountry("DJIBOUTI")]
        [CurrencyDefinition("DJF", "Djibouti Franc", "262", 0)]
        DJF = 262,
        [CurrencyCountry("DENMARK")]
        [CurrencyCountry("FAROE ISLANDS (THE)")]
        [CurrencyCountry("GREENLAND")]
        [CurrencyDefinition("DKK", "Danish Krone", "208", 2)]
        DKK = 208,
        [CurrencyCountry("DOMINICAN REPUBLIC (THE)")]
        [CurrencyDefinition("DOP", "Dominican Peso", "214", 2)]
        DOP = 214,
        [CurrencyCountry("ALGERIA")]
        [CurrencyDefinition("DZD", "Algerian Dinar", "012", 2)]
        DZD = 012,
        [CurrencyCountry("EGYPT")]
        [CurrencyDefinition("EGP", "Egyptian Pound", "818", 2)]
        EGP = 818,
        [CurrencyCountry("ERITREA")]
        [CurrencyDefinition("ERN", "Nakfa", "232", 2)]
        ERN = 232,
        [CurrencyCountry("ETHIOPIA")]
        [CurrencyDefinition("ETB", "Ethiopian Birr", "230", 2)]
        ETB = 230,
        [CurrencyCountry("ÅLAND ISLANDS")]
        [CurrencyCountry("ANDORRA")]
        [CurrencyCountry("AUSTRIA")]
        [CurrencyCountry("BELGIUM")]
        [CurrencyCountry("CYPRUS")]
        [CurrencyCountry("ESTONIA")]
        [CurrencyCountry("EUROPEAN UNION")]
        [CurrencyCountry("FINLAND")]
        [CurrencyCountry("FRANCE")]
        [CurrencyCountry("FRENCH GUIANA")]
        [CurrencyCountry("FRENCH SOUTHERN TERRITORIES (THE)")]
        [CurrencyCountry("GERMANY")]
        [CurrencyCountry("GREECE")]
        [CurrencyCountry("GUADELOUPE")]
        [CurrencyCountry("HOLY SEE (THE)")]
        [CurrencyCountry("IRELAND")]
        [CurrencyCountry("ITALY")]
        [CurrencyCountry("LATVIA")]
        [CurrencyCountry("LITHUANIA")]
        [CurrencyCountry("LUXEMBOURG")]
        [CurrencyCountry("MALTA")]
        [CurrencyCountry("MARTINIQUE")]
        [CurrencyCountry("MAYOTTE")]
        [CurrencyCountry("MONACO")]
        [CurrencyCountry("MONTENEGRO")]
        [CurrencyCountry("NETHERLANDS (THE)")]
        [CurrencyCountry("PORTUGAL")]
        [CurrencyCountry("RÉUNION")]
        [CurrencyCountry("SAINT BARTHÉLEMY")]
        [CurrencyCountry("SAINT MARTIN (FRENCH PART)")]
        [CurrencyCountry("SAINT PIERRE AND MIQUELON")]
        [CurrencyCountry("SAN MARINO")]
        [CurrencyCountry("SLOVAKIA")]
        [CurrencyCountry("SLOVENIA")]
        [CurrencyCountry("SPAIN")]
        [CurrencyDefinition("EUR", "Euro", "978", 2)]
        EUR = 978,
        [CurrencyCountry("FIJI")]
        [CurrencyDefinition("FJD", "Fiji Dollar", "242", 2)]
        FJD = 242,
        [CurrencyCountry("FALKLAND ISLANDS (THE) [MALVINAS]")]
        [CurrencyDefinition("FKP", "Falkland Islands Pound", "238", 2)]
        FKP = 238,
        [CurrencyCountry("GUERNSEY")]
        [CurrencyCountry("ISLE OF MAN")]
        [CurrencyCountry("JERSEY")]
        [CurrencyCountry("UNITED KINGDOM OF GREAT BRITAIN AND NORTHERN IRELAND (THE)")]
        [CurrencyDefinition("GBP", "Pound Sterling", "826", 2)]
        GBP = 826,
        [CurrencyCountry("GEORGIA")]
        [CurrencyDefinition("GEL", "Lari", "981", 2)]
        GEL = 981,
        [CurrencyCountry("GHANA")]
        [CurrencyDefinition("GHS", "Ghana Cedi", "936", 2)]
        GHS = 936,
        [CurrencyCountry("GIBRALTAR")]
        [CurrencyDefinition("GIP", "Gibraltar Pound", "292", 2)]
        GIP = 292,
        [CurrencyCountry("GAMBIA (THE)")]
        [CurrencyDefinition("GMD", "Dalasi", "270", 2)]
        GMD = 270,
        [CurrencyCountry("GUINEA")]
        [CurrencyDefinition("GNF", "Guinea Franc", "324", 0)]
        GNF = 324,
        [CurrencyCountry("GUATEMALA")]
        [CurrencyDefinition("GTQ", "Quetzal", "320", 2)]
        GTQ = 320,
        [CurrencyCountry("GUYANA")]
        [CurrencyDefinition("GYD", "Guyana Dollar", "328", 2)]
        GYD = 328,
        [CurrencyCountry("HONG KONG")]
        [CurrencyDefinition("HKD", "Hong Kong Dollar", "344", 2)]
        HKD = 344,
        [CurrencyCountry("HONDURAS")]
        [CurrencyDefinition("HNL", "Lempira", "340", 2)]
        HNL = 340,
        [CurrencyCountry("CROATIA")]
        [CurrencyDefinition("HRK", "Kuna", "191", 2)]
        HRK = 191,
        [CurrencyCountry("HAITI")]
        [CurrencyDefinition("HTG", "Gourde", "332", 2)]
        HTG = 332,
        [CurrencyCountry("HUNGARY")]
        [CurrencyDefinition("HUF", "Forint", "348", 2)]
        HUF = 348,
        [CurrencyCountry("SWITZERLAND")]
        [CurrencyDefinition("CHE", "WIR Euro", "947", 2)]
        CHE = 947,
        [CurrencyCountry("LIECHTENSTEIN")]
        [CurrencyCountry("SWITZERLAND")]
        [CurrencyDefinition("CHF", "Swiss Franc", "756", 2)]
        CHF = 756,
        [CurrencyCountry("SWITZERLAND")]
        [CurrencyDefinition("CHW", "WIR Franc", "948", 2)]
        CHW = 948,
        [CurrencyCountry("INDONESIA")]
        [CurrencyDefinition("IDR", "Rupiah", "360", 2)]
        IDR = 360,
        [CurrencyCountry("ISRAEL")]
        [CurrencyDefinition("ILS", "New Israeli Sheqel", "376", 2)]
        ILS = 376,
        [CurrencyCountry("BHUTAN")]
        [CurrencyCountry("INDIA")]
        [CurrencyDefinition("INR", "Indian Rupee", "356", 2)]
        INR = 356,
        [CurrencyCountry("IRAQ")]
        [CurrencyDefinition("IQD", "Iraqi Dinar", "368", 3)]
        IQD = 368,
        [CurrencyCountry("IRAN (ISLAMIC REPUBLIC OF)")]
        [CurrencyDefinition("IRR", "Iranian Rial", "364", 2)]
        IRR = 364,
        [CurrencyCountry("ICELAND")]
        [CurrencyDefinition("ISK", "Iceland Krona", "352", 0)]
        ISK = 352,
        [CurrencyCountry("JAMAICA")]
        [CurrencyDefinition("JMD", "Jamaican Dollar", "388", 2)]
        JMD = 388,
        [CurrencyCountry("JORDAN")]
        [CurrencyDefinition("JOD", "Jordanian Dinar", "400", 3)]
        JOD = 400,
        [CurrencyCountry("JAPAN")]
        [CurrencyDefinition("JPY", "Yen", "392", 0)]
        JPY = 392,
        [CurrencyCountry("KENYA")]
        [CurrencyDefinition("KES", "Kenyan Shilling", "404", 2)]
        KES = 404,
        [CurrencyCountry("KYRGYZSTAN")]
        [CurrencyDefinition("KGS", "Som", "417", 2)]
        KGS = 417,
        [CurrencyCountry("CAMBODIA")]
        [CurrencyDefinition("KHR", "Riel", "116", 2)]
        KHR = 116,
        [CurrencyCountry("COMOROS (THE)")]
        [CurrencyDefinition("KMF", "Comoro Franc", "174", 0)]
        KMF = 174,
        [CurrencyCountry("KOREA (THE DEMOCRATIC PEOPLE’S REPUBLIC OF)")]
        [CurrencyDefinition("KPW", "North Korean Won", "408", 2)]
        KPW = 408,
        [CurrencyCountry("KOREA (THE REPUBLIC OF)")]
        [CurrencyDefinition("KRW", "Won", "410", 0)]
        KRW = 410,
        [CurrencyCountry("KUWAIT")]
        [CurrencyDefinition("KWD", "Kuwaiti Dinar", "414", 3)]
        KWD = 414,
        [CurrencyCountry("CAYMAN ISLANDS (THE)")]
        [CurrencyDefinition("KYD", "Cayman Islands Dollar", "136", 2)]
        KYD = 136,
        [CurrencyCountry("KAZAKHSTAN")]
        [CurrencyDefinition("KZT", "Tenge", "398", 2)]
        KZT = 398,
        [CurrencyCountry("LAO PEOPLE’S DEMOCRATIC REPUBLIC (THE)")]
        [CurrencyDefinition("LAK", "Kip", "418", 2)]
        LAK = 418,
        [CurrencyCountry("LEBANON")]
        [CurrencyDefinition("LBP", "Lebanese Pound", "422", 2)]
        LBP = 422,
        [CurrencyCountry("SRI LANKA")]
        [CurrencyDefinition("LKR", "Sri Lanka Rupee", "144", 2)]
        LKR = 144,
        [CurrencyCountry("LIBERIA")]
        [CurrencyDefinition("LRD", "Liberian Dollar", "430", 2)]
        LRD = 430,
        [CurrencyCountry("LESOTHO")]
        [CurrencyDefinition("LSL", "Loti", "426", 2)]
        LSL = 426,
        [CurrencyCountry("LIBYA")]
        [CurrencyDefinition("LYD", "Libyan Dinar", "434", 3)]
        LYD = 434,
        [CurrencyCountry("MOROCCO")]
        [CurrencyCountry("WESTERN SAHARA")]
        [CurrencyDefinition("MAD", "Moroccan Dirham", "504", 2)]
        MAD = 504,
        [CurrencyCountry("MOLDOVA (THE REPUBLIC OF)")]
        [CurrencyDefinition("MDL", "Moldovan Leu", "498", 2)]
        MDL = 498,
        [CurrencyCountry("MADAGASCAR")]
        [CurrencyDefinition("MGA", "Malagasy Ariary", "969", 2)]
        MGA = 969,
        [CurrencyCountry("MACEDONIA (THE FORMER YUGOSLAV REPUBLIC OF)")]
        [CurrencyDefinition("MKD", "Denar", "807", 2)]
        MKD = 807,
        [CurrencyCountry("MYANMAR")]
        [CurrencyDefinition("MMK", "Kyat", "104", 2)]
        MMK = 104,
        [CurrencyCountry("MONGOLIA")]
        [CurrencyDefinition("MNT", "Tugrik", "496", 2)]
        MNT = 496,
        [CurrencyCountry("MACAO")]
        [CurrencyDefinition("MOP", "Pataca", "446", 2)]
        MOP = 446,
        [CurrencyCountry("MAURITANIA")]
        [CurrencyDefinition("MRO", "Ouguiya", "478", 2)]
        MRO = 478,
        [CurrencyCountry("MAURITIUS")]
        [CurrencyDefinition("MUR", "Mauritius Rupee", "480", 2)]
        MUR = 480,
        [CurrencyCountry("MALDIVES")]
        [CurrencyDefinition("MVR", "Rufiyaa", "462", 2)]
        MVR = 462,
        [CurrencyCountry("MALAWI")]
        [CurrencyDefinition("MWK", "Malawi Kwacha", "454", 2)]
        MWK = 454,
        [CurrencyCountry("MEXICO")]
        [CurrencyDefinition("MXN", "Mexican Peso", "484", 2)]
        MXN = 484,
        [CurrencyCountry("MEXICO")]
        [CurrencyDefinition("MXV", "Mexican Unidad de Inversion (UDI)", "979", 2)]
        MXV = 979,
        [CurrencyCountry("MALAYSIA")]
        [CurrencyDefinition("MYR", "Malaysian Ringgit", "458", 2)]
        MYR = 458,
        [CurrencyCountry("MOZAMBIQUE")]
        [CurrencyDefinition("MZN", "Mozambique Metical", "943", 2)]
        MZN = 943,
        [CurrencyCountry("NAMIBIA")]
        [CurrencyDefinition("NAD", "Namibia Dollar", "516", 2)]
        NAD = 516,
        [CurrencyCountry("NIGERIA")]
        [CurrencyDefinition("NGN", "Naira", "566", 2)]
        NGN = 566,
        [CurrencyCountry("NICARAGUA")]
        [CurrencyDefinition("NIO", "Cordoba Oro", "558", 2)]
        NIO = 558,
        [CurrencyCountry("BOUVET ISLAND")]
        [CurrencyCountry("NORWAY")]
        [CurrencyCountry("SVALBARD AND JAN MAYEN")]
        [CurrencyDefinition("NOK", "Norwegian Krone", "578", 2)]
        NOK = 578,
        [CurrencyCountry("NEPAL")]
        [CurrencyDefinition("NPR", "Nepalese Rupee", "524", 2)]
        NPR = 524,
        [CurrencyCountry("COOK ISLANDS (THE)")]
        [CurrencyCountry("NEW ZEALAND")]
        [CurrencyCountry("NIUE")]
        [CurrencyCountry("PITCAIRN")]
        [CurrencyCountry("TOKELAU")]
        [CurrencyDefinition("NZD", "New Zealand Dollar", "554", 2)]
        NZD = 554,
        [CurrencyCountry("OMAN")]
        [CurrencyDefinition("OMR", "Rial Omani", "512", 3)]
        OMR = 512,
        [CurrencyCountry("PANAMA")]
        [CurrencyDefinition("PAB", "Balboa", "590", 2)]
        PAB = 590,
        [CurrencyCountry("PERU")]
        [CurrencyDefinition("PEN", "Sol", "604", 2)]
        PEN = 604,
        [CurrencyCountry("PAPUA NEW GUINEA")]
        [CurrencyDefinition("PGK", "Kina", "598", 2)]
        PGK = 598,
        [CurrencyCountry("PHILIPPINES (THE)")]
        [CurrencyDefinition("PHP", "Philippine Peso", "608", 2)]
        PHP = 608,
        [CurrencyCountry("PAKISTAN")]
        [CurrencyDefinition("PKR", "Pakistan Rupee", "586", 2)]
        PKR = 586,
        [CurrencyCountry("POLAND")]
        [CurrencyDefinition("PLN", "Zloty", "985", 2)]
        PLN = 985,
        [CurrencyCountry("PARAGUAY")]
        [CurrencyDefinition("PYG", "Guarani", "600", 0)]
        PYG = 600,
        [CurrencyCountry("QATAR")]
        [CurrencyDefinition("QAR", "Qatari Rial", "634", 2)]
        QAR = 634,
        [CurrencyCountry("ROMANIA")]
        [CurrencyDefinition("RON", "Romanian Leu", "946", 2)]
        RON = 946,
        [CurrencyCountry("SERBIA")]
        [CurrencyDefinition("RSD", "Serbian Dinar", "941", 2)]
        RSD = 941,
        [CurrencyCountry("RUSSIAN FEDERATION (THE)")]
        [CurrencyDefinition("RUB", "Russian Ruble", "643", 2)]
        RUB = 643,
        [CurrencyCountry("RWANDA")]
        [CurrencyDefinition("RWF", "Rwanda Franc", "646", 0)]
        RWF = 646,
        [CurrencyCountry("SAUDI ARABIA")]
        [CurrencyDefinition("SAR", "Saudi Riyal", "682", 2)]
        SAR = 682,
        [CurrencyCountry("SOLOMON ISLANDS")]
        [CurrencyDefinition("SBD", "Solomon Islands Dollar", "090", 2)]
        SBD = 090,
        [CurrencyCountry("SEYCHELLES")]
        [CurrencyDefinition("SCR", "Seychelles Rupee", "690", 2)]
        SCR = 690,
        [CurrencyCountry("SUDAN (THE)")]
        [CurrencyDefinition("SDG", "Sudanese Pound", "938", 2)]
        SDG = 938,
        [CurrencyCountry("SWEDEN")]
        [CurrencyDefinition("SEK", "Swedish Krona", "752", 2)]
        SEK = 752,
        [CurrencyCountry("SINGAPORE")]
        [CurrencyDefinition("SGD", "Singapore Dollar", "702", 2)]
        SGD = 702,
        [CurrencyCountry("SAINT HELENA, ASCENSION AND TRISTAN DA CUNHA")]
        [CurrencyDefinition("SHP", "Saint Helena Pound", "654", 2)]
        SHP = 654,
        [CurrencyCountry("SIERRA LEONE")]
        [CurrencyDefinition("SLL", "Leone", "694", 2)]
        SLL = 694,
        [CurrencyCountry("SOMALIA")]
        [CurrencyDefinition("SOS", "Somali Shilling", "706", 2)]
        SOS = 706,
        [CurrencyCountry("SURINAME")]
        [CurrencyDefinition("SRD", "Surinam Dollar", "968", 2)]
        SRD = 968,
        [CurrencyCountry("SOUTH SUDAN")]
        [CurrencyDefinition("SSP", "South Sudanese Pound", "728", 2)]
        SSP = 728,
        [CurrencyCountry("SAO TOME AND PRINCIPE")]
        [CurrencyDefinition("STD", "Dobra", "678", 2)]
        STD = 678,
        [CurrencyCountry("EL SALVADOR")]
        [CurrencyDefinition("SVC", "El Salvador Colon", "222", 2)]
        SVC = 222,
        [CurrencyCountry("SYRIAN ARAB REPUBLIC")]
        [CurrencyDefinition("SYP", "Syrian Pound", "760", 2)]
        SYP = 760,
        [CurrencyCountry("SWAZILAND")]
        [CurrencyDefinition("SZL", "Lilangeni", "748", 2)]
        SZL = 748,
        [CurrencyCountry("THAILAND")]
        [CurrencyDefinition("THB", "Baht", "764", 2)]
        THB = 764,
        [CurrencyCountry("TAJIKISTAN")]
        [CurrencyDefinition("TJS", "Somoni", "972", 2)]
        TJS = 972,
        [CurrencyCountry("TURKMENISTAN")]
        [CurrencyDefinition("TMT", "Turkmenistan New Manat", "934", 2)]
        TMT = 934,
        [CurrencyCountry("TUNISIA")]
        [CurrencyDefinition("TND", "Tunisian Dinar", "788", 3)]
        TND = 788,
        [CurrencyCountry("TONGA")]
        [CurrencyDefinition("TOP", "Pa’anga", "776", 2)]
        TOP = 776,
        [CurrencyCountry("TURKEY")]
        [CurrencyDefinition("TRY", "Turkish Lira", "949", 2)]
        TRY = 949,
        [CurrencyCountry("TRINIDAD AND TOBAGO")]
        [CurrencyDefinition("TTD", "Trinidad and Tobago Dollar", "780", 2)]
        TTD = 780,
        [CurrencyCountry("TAIWAN (PROVINCE OF CHINA)")]
        [CurrencyDefinition("TWD", "New Taiwan Dollar", "901", 2)]
        TWD = 901,
        [CurrencyCountry("TANZANIA, UNITED REPUBLIC OF")]
        [CurrencyDefinition("TZS", "Tanzanian Shilling", "834", 2)]
        TZS = 834,
        [CurrencyCountry("UKRAINE")]
        [CurrencyDefinition("UAH", "Hryvnia", "980", 2)]
        UAH = 980,
        [CurrencyCountry("UGANDA")]
        [CurrencyDefinition("UGX", "Uganda Shilling", "800", 0)]
        UGX = 800,
        [CurrencyCountry("AMERICAN SAMOA")]
        [CurrencyCountry("BONAIRE, SINT EUSTATIUS AND SABA")]
        [CurrencyCountry("BRITISH INDIAN OCEAN TERRITORY (THE)")]
        [CurrencyCountry("ECUADOR")]
        [CurrencyCountry("EL SALVADOR")]
        [CurrencyCountry("GUAM")]
        [CurrencyCountry("HAITI")]
        [CurrencyCountry("MARSHALL ISLANDS (THE)")]
        [CurrencyCountry("MICRONESIA (FEDERATED STATES OF)")]
        [CurrencyCountry("NORTHERN MARIANA ISLANDS (THE)")]
        [CurrencyCountry("PALAU")]
        [CurrencyCountry("PANAMA")]
        [CurrencyCountry("PUERTO RICO")]
        [CurrencyCountry("TIMOR-LESTE")]
        [CurrencyCountry("TURKS AND CAICOS ISLANDS (THE)")]
        [CurrencyCountry("UNITED STATES MINOR OUTLYING ISLANDS (THE)")]
        [CurrencyCountry("UNITED STATES OF AMERICA (THE)")]
        [CurrencyCountry("VIRGIN ISLANDS (BRITISH)")]
        [CurrencyCountry("VIRGIN ISLANDS (U.S.)")]
        [CurrencyDefinition("USD", "US Dollar", "840", 2)]
        USD = 840,
        [CurrencyCountry("UNITED STATES OF AMERICA (THE)")]
        [CurrencyDefinition("USN", "US Dollar (Next day)", "997", 2)]
        USN = 997,
        [CurrencyCountry("URUGUAY")]
        [CurrencyDefinition("UYI", "Uruguay Peso en Unidades Indexadas (URUIURUI)", "940", 0)]
        UYI = 940,
        [CurrencyCountry("URUGUAY")]
        [CurrencyDefinition("UYU", "Peso Uruguayo", "858", 2)]
        UYU = 858,
        [CurrencyCountry("UZBEKISTAN")]
        [CurrencyDefinition("UZS", "Uzbekistan Sum", "860", 2)]
        UZS = 860,
        [CurrencyCountry("VENEZUELA (BOLIVARIAN REPUBLIC OF)")]
        [CurrencyDefinition("VEF", "Bolívar", "937", 2)]
        VEF = 937,
        [CurrencyCountry("VIET NAM")]
        [CurrencyDefinition("VND", "Dong", "704", 0)]
        VND = 704,
        [CurrencyCountry("VANUATU")]
        [CurrencyDefinition("VUV", "Vatu", "548", 0)]
        VUV = 548,
        [CurrencyCountry("SAMOA")]
        [CurrencyDefinition("WST", "Tala", "882", 2)]
        WST = 882,
        [CurrencyCountry("CAMEROON")]
        [CurrencyCountry("CENTRAL AFRICAN REPUBLIC (THE)")]
        [CurrencyCountry("CHAD")]
        [CurrencyCountry("CONGO (THE)")]
        [CurrencyCountry("EQUATORIAL GUINEA")]
        [CurrencyCountry("GABON")]
        [CurrencyDefinition("XAF", "CFA Franc BEAC", "950", 0)]
        XAF = 950,
        [CurrencyCountry("ZZ11_Silver")]
        [CurrencyDefinition("XAG", "Silver", "961", -1)]
        XAG = 961,
        [CurrencyCountry("ZZ08_Gold")]
        [CurrencyDefinition("XAU", "Gold", "959", -1)]
        XAU = 959,
        [CurrencyCountry("ZZ01_Bond Markets Unit European_EURCO")]
        [CurrencyDefinition("XBA", "Bond Markets Unit European Composite Unit (EURCO)", "955", -1)]
        XBA = 955,
        [CurrencyCountry("ZZ02_Bond Markets Unit European_EMU-6")]
        [CurrencyDefinition("XBB", "Bond Markets Unit European Monetary Unit (E.M.U.-6)", "956", -1)]
        XBB = 956,
        [CurrencyCountry("ZZ03_Bond Markets Unit European_EUA-9")]
        [CurrencyDefinition("XBC", "Bond Markets Unit European Unit of Account 9 (E.U.A.-9)", "957", -1)]
        XBC = 957,
        [CurrencyCountry("ZZ04_Bond Markets Unit European_EUA-17")]
        [CurrencyDefinition("XBD", "Bond Markets Unit European Unit of Account 17 (E.U.A.-17)", "958", -1)]
        XBD = 958,
        [CurrencyCountry("ANGUILLA")]
        [CurrencyCountry("ANTIGUA AND BARBUDA")]
        [CurrencyCountry("DOMINICA")]
        [CurrencyCountry("GRENADA")]
        [CurrencyCountry("MONTSERRAT")]
        [CurrencyCountry("SAINT KITTS AND NEVIS")]
        [CurrencyCountry("SAINT LUCIA")]
        [CurrencyCountry("SAINT VINCENT AND THE GRENADINES")]
        [CurrencyDefinition("XCD", "East Caribbean Dollar", "951", 2)]
        XCD = 951,
        [CurrencyCountry("INTERNATIONAL MONETARY FUND (IMF) ")]
        [CurrencyDefinition("XDR", "SDR (Special Drawing Right)", "960", -1)]
        XDR = 960,
        [CurrencyCountry("BENIN")]
        [CurrencyCountry("BURKINA FASO")]
        [CurrencyCountry("CÔTE D'IVOIRE")]
        [CurrencyCountry("GUINEA-BISSAU")]
        [CurrencyCountry("MALI")]
        [CurrencyCountry("NIGER (THE)")]
        [CurrencyCountry("SENEGAL")]
        [CurrencyCountry("TOGO")]
        [CurrencyDefinition("XOF", "CFA Franc BCEAO", "952", 0)]
        XOF = 952,
        [CurrencyCountry("ZZ09_Palladium")]
        [CurrencyDefinition("XPD", "Palladium", "964", -1)]
        XPD = 964,
        [CurrencyCountry("FRENCH POLYNESIA")]
        [CurrencyCountry("NEW CALEDONIA")]
        [CurrencyCountry("WALLIS AND FUTUNA")]
        [CurrencyDefinition("XPF", "CFP Franc", "953", 0)]
        XPF = 953,
        [CurrencyCountry("ZZ10_Platinum")]
        [CurrencyDefinition("XPT", "Platinum", "962", -1)]
        XPT = 962,
        [CurrencyCountry("SISTEMA UNITARIO DE COMPENSACION REGIONAL DE PAGOS \"SUCRE\"")]
        [CurrencyDefinition("XSU", "Sucre", "994", -1)]
        XSU = 994,
        [CurrencyCountry("ZZ06_Testing_Code")]
        [CurrencyDefinition("XTS", "Codes specifically reserved for testing purposes", "963", -1)]
        XTS = 963,
        [CurrencyCountry("MEMBER COUNTRIES OF THE AFRICAN DEVELOPMENT BANK GROUP")]
        [CurrencyDefinition("XUA", "ADB Unit of Account", "965", -1)]
        XUA = 965,
        [CurrencyCountry("ZZ07_No_Currency")]
        [CurrencyDefinition("XXX", "The codes assigned for transactions where no currency is involved", "999", -1)]
        XXX = 999,
        [CurrencyCountry("YEMEN")]
        [CurrencyDefinition("YER", "Yemeni Rial", "886", 2)]
        YER = 886,
        [CurrencyCountry("LESOTHO")]
        [CurrencyCountry("NAMIBIA")]
        [CurrencyCountry("SOUTH AFRICA")]
        [CurrencyDefinition("ZAR", "Rand", "710", 2)]
        ZAR = 710,
        [CurrencyCountry("ZAMBIA")]
        [CurrencyDefinition("ZMW", "Zambian Kwacha", "967", 2)]
        ZMW = 967,
        [CurrencyCountry("ZIMBABWE")]
        [CurrencyDefinition("ZWL", "Zimbabwe Dollar", "932", 2)]
        ZWL = 932,
    }
}
